import {
  Landmark,
  CreditCard,
  ArrowLeftRight,
  Wallet,
  Store,
  Phone,
  Monitor,
  LayoutTemplate,
  Globe,
  Smartphone,
  Users,
  Database,
  Sparkles,
  Zap,
  Activity,
  Plug,
  Languages,
  ShieldCheck,
  Lock,
  Banknote,
  Code,
  MessageCircle,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { IconKey } from '../data/pricing'

export const ICONS: Record<IconKey, LucideIcon> = {
  landmark: Landmark,
  card: CreditCard,
  transfer: ArrowLeftRight,
  wallet: Wallet,
  store: Store,
  phone: Phone,
  monitor: Monitor,
  layout: LayoutTemplate,
  globe: Globe,
  mobile: Smartphone,
  users: Users,
  database: Database,
  sparkles: Sparkles,
  zap: Zap,
  activity: Activity,
  plug: Plug,
  languages: Languages,
  shield: ShieldCheck,
  lock: Lock,
  banknote: Banknote,
  code: Code,
  chat: MessageCircle,
}